---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	model(model)
	tools(tools)
	TodoListMiddleware\2eafter_model(TodoListMiddleware.after_model)
	PatchToolCallsMiddleware\2ebefore_agent(PatchToolCallsMiddleware.before_agent)
	log_before_agent\2ebefore_agent(log_before_agent.before_agent)
	inject_intent_decomposition_context\2ebefore_model(inject_intent_decomposition_context.before_model)
	SummarizationMiddleware\2ebefore_model(SummarizationMiddleware.before_model)
	HumanInTheLoopMiddleware\2eafter_model(HumanInTheLoopMiddleware.after_model)
	postprocess_model_answer\2eafter_model(postprocess_model_answer.after_model)
	log_after_agent\2eafter_agent(log_after_agent.after_agent)
	__end__([<p>__end__</p>]):::last
	HumanInTheLoopMiddleware\2eafter_model --> TodoListMiddleware\2eafter_model;
	PatchToolCallsMiddleware\2ebefore_agent --> log_before_agent\2ebefore_agent;
	SummarizationMiddleware\2ebefore_model --> model;
	TodoListMiddleware\2eafter_model -.-> inject_intent_decomposition_context\2ebefore_model;
	TodoListMiddleware\2eafter_model -.-> log_after_agent\2eafter_agent;
	TodoListMiddleware\2eafter_model -.-> tools;
	__start__ --> PatchToolCallsMiddleware\2ebefore_agent;
	inject_intent_decomposition_context\2ebefore_model --> SummarizationMiddleware\2ebefore_model;
	log_before_agent\2ebefore_agent --> inject_intent_decomposition_context\2ebefore_model;
	model --> postprocess_model_answer\2eafter_model;
	postprocess_model_answer\2eafter_model --> HumanInTheLoopMiddleware\2eafter_model;
	tools -.-> inject_intent_decomposition_context\2ebefore_model;
	log_after_agent\2eafter_agent --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
